Resubmit of failed comments
scm-manager/scm-issuetracker-plugin pull request #12
Opened 2021-04-20 09:46 UTC by sdorra

## Proposed changes

Ports the resubmit feature from the jira plugin to the issue tracker plugin to make it available for every issue tracker. The feature includes resending of failed comments and notifications.

### Your checklist for this pull request

- [X] PR is well described and the description can be used as commit message on squash
- [X] Related issues linked to PR if existing and labels set
- [X] Target branch is not master (in most cases develop should bet the target of choice) 
- [X] Code does not conflict with target branch
- [X] New code is covered with unit tests
- [X] [Changelog entry file](https://github.com/scm-manager/changelog#changelog-entry-files) created in `gradle/changelog`
- [X] Definition of Done's fulfilled: [DoD](https://github.com/scm-manager/scm-manager/blob/develop/docs/en/development/definition-of-done.md) // [UI DoD](https://github.com/scm-manager/scm-manager/blob/develop/docs/en/development/ui-dod.md)
- [X] Documentation updated (only necessary for new features or changed behaviour)

### Checklist for branch merge request (not required for forks)

- [ ] Branch is green/blue on [Jenkins](https://oss.cloudogu.com/jenkins/)
- [ ] Quality Gate passed on [SonarQube](https://sonarcloud.io/organizations/scm-manager/projects)

2021-04-20 17:19 UTC, pfeuffer requested changes
Minor remarks only 👍🏽

2021-04-20 17:19 UTC, pfeuffer commented on src/main/js/admin/ResubmitSection.tsx
> +            </td>
The buttons are somewhat out of bounds (or the text in the other columns is not centered enough). Somehow this looks a bit out of order.

2021-04-20 17:19 UTC, pfeuffer commented on src/main/resources/locales/de/plugins.json
> +      "resubmit": "Erneute senden",
Typo..?
```suggestion
      "resubmit": "Erneut senden",
```

2021-04-20 17:19 UTC, pfeuffer commented on src/main/resources/locales/de/plugins.json
> +        "title": "Erneut Senden Konfiguration",
```suggestion
        "title": "Konfiguration für erneutes Senden",
```

2021-04-20 17:19 UTC, pfeuffer commented on src/main/resources/locales/de/plugins.json
> +        "description": "Konfiguration für die Erneute Senden Funktion",
```suggestion
        "description": "Konfiguration für die \"Erneut Senden\" Funktion",
```

2021-04-20 17:19 UTC, pfeuffer commented on src/main/resources/locales/de/plugins.json
> +        "description": "Erneutes senden ausstehender Issue Tracker Kommentare veranlassen und konfigurieren"
```suggestion
        "description": "Erneutes Senden ausstehender Issue Tracker Kommentare veranlassen und konfigurieren"
```

2021-04-20 17:19 UTC, pfeuffer commented on src/main/resources/locales/en/plugins.json
> +    "subtitle": "General Issue Tracker configuration",
Either all caps or not.
```suggestion
    "subtitle": "General issue tracker configuration",
```

2021-04-20 17:19 UTC, pfeuffer commented on src/main/resources/sonia/scm/issuetracker/internal/resubmit/comment-mail.md.mustache
> +The comment can be sent again in the [issue tracker admin section]({{ url }}).
Don't we have a german version for this?

2021-04-20 17:19 UTC, pfeuffer commented on src/main/resources/sonia/scm/issuetracker/internal/resubmit/resubmit-mail.md.mustache
> +Requeued comments can be resend or removed in the [issue tracker admin section]({{ url }}).
Don't we have a german version for this?

2021-04-20 17:19 UTC, pfeuffer commented on src/test/java/sonia/scm/issuetracker/internal/resubmit/EvictingQueueTest.java
> +    assertThat(queue).containsOnly("b", "c");
Had to think twice to distinguish action and checked result here. Think there are two tests hidden inside :-)

2021-04-20 17:19 UTC, pfeuffer commented on src/test/java/sonia/scm/issuetracker/internal/resubmit/ResubmitConfigurationStoreTest.java
> +  @SubjectAware(value = "trillian", permissions = "issuetracker:resubmit:*")
Like this new annotation 👍🏽

2021-04-21 05:44 UTC, sdorra commented on src/main/java/sonia/scm/issuetracker/internal/resubmit/ResubmitProcessor.java
> +      requeue.addAll(queuedComments);
A the moment we store every failed comment, even if the issue tracker does not support resubmitting.

2021-04-21 05:45 UTC, sdorra commented on src/main/java/sonia/scm/issuetracker/internal/resubmit/ResubmitResource.java
> +  public ResubmitConfigurationDto getConfiguration(@Context UriInfo info) {
The name is only used if the `@Operation` has no `operationId`.

2021-04-21 05:45 UTC, sdorra commented on src/main/java/sonia/scm/issuetracker/internal/resubmit/ResubmitResource.java
> +  public Response setConfiguration(@Valid ResubmitConfigurationDto dto) {
The name is only used if the `@Operation` has no `operationId`.

2021-04-21 05:45 UTC, sdorra commented on src/main/java/sonia/scm/issuetracker/internal/resubmit/ResubmitResource.java
> +  public Response resubmit(@PathParam("issueTracker") String issueTracker) {
The name is only used if the `@Operation` has no `operationId`.

2021-04-21 05:45 UTC, sdorra commented on src/main/java/sonia/scm/issuetracker/internal/resubmit/ResubmitResource.java
> +  public Response clear(@PathParam("issueTracker") String issueTracker) {
The name is only used if the `@Operation` has no `operationId`.

2021-04-21 08:28 UTC, pfeuffer commented on src/main/java/sonia/scm/issuetracker/internal/resubmit/ResubmitProcessor.java
> +      requeue.addAll(queuedComments);
Is it wise to requeue them in this case? This sounds like there is no chance to get rid of them and they would have to be dumped sooner or later.

2021-04-21 08:31 UTC, pfeuffer commented on src/main/java/sonia/scm/issuetracker/internal/resubmit/ResubmitResource.java
> +  public ResubmitConfigurationDto getConfiguration(@Context UriInfo info) {
Good tip, thx 👍🏽

2021-04-21 08:52 UTC, pfeuffer requested changes
Small last remarks

2021-04-21 08:52 UTC, pfeuffer commented on src/main/java/sonia/scm/issuetracker/internal/resubmit/ResubmitConfigurationStore.java
> +    return store.getOptional().orElse(new ResubmitConfiguration());
```suggestion
    return store.getOptional().orElseGet(() -> new ResubmitConfiguration());
```

2021-04-21 08:52 UTC, pfeuffer commented on src/main/js/admin/ResubmitSection.tsx
> +            <td>{resubmit.queueSize}</td>
These cells should be centered vertically to align them with the buttons

2021-04-21 08:52 UTC, pfeuffer commented on src/main/resources/locales/de/plugins.json
> +        "submit": "Konfiguration aktualisieren"
```suggestion
        "submit": "Speichern"
```

2021-04-21 08:52 UTC, pfeuffer commented on src/main/resources/locales/en/plugins.json
> +        "submit": "Update configuration"
```suggestion
        "submit": "Submit"
```

2021-04-21 08:52 UTC, pfeuffer commented on src/main/resources/sonia/scm/issuetracker/internal/resubmit/resubmit-mail_de.mustache
> +# Erneutes Senden der Komemntare für Issue Tracker {{ issueTracker }}
```suggestion
# Erneutes Senden der Kommentare für Issue Tracker {{ issueTracker }}
```

2021-04-21 08:52 UTC, pfeuffer commented on src/main/resources/sonia/scm/issuetracker/internal/resubmit/resubmit-mail_de.mustache
> +[Issue Tracker Admin Oberfläche]({{ url }}) erneute gesendet oder gelöscht werden.
```suggestion
[Issue Tracker Admin Oberfläche]({{ url }}) erneut gesendet oder gelöscht werden.
```

2021-04-22 07:50 UTC, merged